= 希尔排序

希尔排序是link:../insertion_sort/[插入排序]的改进版。将要排序的数组切分成若干个较小的逻辑子数组，然后使用插入排序对子数组进行排序。

假设我们想使用希尔排序对数组 `[64, 20, 50, 33, 72, 10, 23, -1, 4]` 进行排序。我们首先可以将它切分成如下4个逻辑子列表：
----
sublist 0:  [ 64, xx, xx, xx, 72, xx, xx, xx, 4  ]
sublist 1:  [ xx, 20, xx, xx, xx, 10, xx, xx, xx ]
sublist 2:  [ xx, xx, 50, xx, xx, xx, 23, xx, xx ]
sublist 3:  [ xx, xx, xx, 33, xx, xx, xx, -1, xx ]
----
从中可以看出，原数组的每4个元素组成一个新的子列表，为什么是4？它是数组长度 `9/2` 得来的，得到的4我们称它为__步长 (gap)__。

通过对每一个子列表进行插入排序，得到：
----
sublist 0:  [  4, xx, xx, xx, 64, xx, xx, xx, 72 ]
sublist 1:  [ xx, 10, xx, xx, xx, 20, xx, xx, xx ]
sublist 2:  [ xx, xx, 23, xx, xx, xx, 50, xx, xx ]
sublist 3:  [ xx, xx, xx, -1, xx, xx, xx, 33, xx ]
----
完整的数组是这样的：
----
[ 4, 10, 23, -1, 64, 20, 50, 33, 72 ]
----

它还没有完全排序，不过比之前更加有序了，接下来进行下一轮排序。我们需要继续缩小步长， `步长/2` 的结果是2，即这时的步长是2，每两个元素组成一个新的数组。这一轮将数组切分成两个逻辑子列表：
----
sublist 0:  [  4, xx, 23, xx, 64, xx, 50, xx, 72 ]
sublist 1:  [ xx, 10, xx, -1, xx, 20, xx, 33, xx ]
----

分别对两个子列表进行插入排序后，得到：
----
sublist 0:  [  4, xx, 23, xx, 50, xx, 64, xx, 72 ]
sublist 1:  [ xx, -1, xx, 10, xx, 20, xx, 33, xx ]
----

完整的数组是这样的：
----
[ 4, -1, 23, 10, 50, 20, 64, 33, 72 ]
----

这一轮排序之后，数组比之前更加有序了。不过还没完，要做到完全排序，需要最终相邻元素两两比较才能确定。`步长/2` 的结果是1，步长为1即意味着是最后一轮排序，这时候的唯一逻辑子列表即完整列表：
----
sublist 0:  [ 4, -1, 23, 10, 50, 20, 64, 33, 72 ]
----

继续进行插入排序之后，得到最终结果：
----
[ -1, 4, 10, 20, 23, 33, 50, 64, 72 ]
----

== 代码
https://github.com/oobot/learning-algorithms/blob/75e110478e658518aa41c6dfa4b6eb3ced8e5fc0/src/sort/shell_sort/mod.rs#L2-L20

== 步长序列
步长序列确定步长的初始大小以及每次迭代是如何变小的。良好的步长序列对于希尔排序表现良好非常重要。
上面例子使用步长是希尔最初建议的：初始值是数组大小的一半，然后每次除以2，直至为1。虽然这样取值可以比 O(_n_^2^) 类的算法（插入排序）更好，但仍然有减少平均时间和最差时间的余地。

____
已知的最好步长序列是由 https://web.archive.org/web/20190427051559/http://faculty.simpson.edu/lydia.sinapova/www/cmsc250/LN250_Weiss/L12-ShellSort.htm#increments[Sedgewick 提出的](1, 5, 19, 41, 109,...)。这个序列的项，从第0项开始，偶数来自 9 × 4^i^ − 9 × 2^i^ + 1 和奇数来自 2^i^ + 2 × (2^i^ + 2 − 3 ) + 1 这两个算式。
____

== 性能
希尔排序是**不稳定的排序**。对于中等规模的数据，希尔排序通常可以达到 O(_n_ log__n__)。而对于大规模数据，它的性能性能通常是 O(_n_^2^)。

* https://www.cnblogs.com/chengxiao/p/6104371.html[扩展阅读1]
* https://zh.wikipedia.org/zh-hans/%E5%B8%8C%E5%B0%94%E6%8E%92%E5%BA%8F[扩展阅读2]